// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: downstream_service.proto

package org.grpcmock.examples.v1;

public final class DownstreamServiceProto {
  private DownstreamServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcmock_examples_v1_GetDownstreamMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcmock_examples_v1_GetDownstreamMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcmock_examples_v1_GetDownstreamMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcmock_examples_v1_GetDownstreamMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030downstream_service.proto\022\024grpcmock.exa" +
      "mples.v1\".\n\033GetDownstreamMessageRequest\022" +
      "\017\n\007message\030\001 \001(\t\"/\n\034GetDownstreamMessage" +
      "Response\022\017\n\007message\030\001 \001(\t2\222\001\n\021Downstream" +
      "Service\022}\n\024GetDownstreamMessage\0221.grpcmo" +
      "ck.examples.v1.GetDownstreamMessageReque" +
      "st\0322.grpcmock.examples.v1.GetDownstreamM" +
      "essageResponseB4\n\030org.grpcmock.examples." +
      "v1B\026DownstreamServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpcmock_examples_v1_GetDownstreamMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcmock_examples_v1_GetDownstreamMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcmock_examples_v1_GetDownstreamMessageRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_grpcmock_examples_v1_GetDownstreamMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcmock_examples_v1_GetDownstreamMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcmock_examples_v1_GetDownstreamMessageResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
