// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: downstream_service.proto

package org.grpcmock.examples.v1;

public interface GetDownstreamMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcmock.examples.v1.GetDownstreamMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
